name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Python configuration
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies 
        run: |
          pip install -r requirements.txt

      - name: Lint with Ruff
        run: ruff check .

      - name: Tests with pytest
        run: pytest 
